spring:
  redis:
    database: 15
    databaseListen: 14
    host: 47.110.84.21
    port: 6379
    passWord: xbz_redis@2019
    timeout: 15000
    maxActive: 8
    maxWait: -1
    maxIdle: 8
    minIdle: 0


swagger:
    enabled: true