spring:
  redis:
    password:
    host: 127.0.0.1
    port: 6379
    timeout: 15000
    database: 0
    databaseListen: 1
    # Connection URL, will override host, port and password (user will be ignored), e.g. redis://user:password@example.com:6379
    #url:
    ssl: false
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
        #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
        time-between-eviction-runs: 30000

swagger:
    enabled: true