spring:
  redis:
    cluster:
      nodes:
        - 127.0.0.1:20000
        - 127.0.0.1:20001
        - 127.0.0.1:20002
      max-redirects: 3 # 获取失败 最大重定向次数
    password:
    timeout: 15000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
        #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
        time-between-eviction-runs: 30000

swagger:
    enabled: true