spring:

  redisson:
    password: xbz_redis@2019

    #单机
    address: redis://47.110.84.21:6379
    #哨兵
#    masterName: mymaster
#    sentinelAddresses: redis://127.0.0.1:6379,redis://127.0.0.1:6380,redis://127.0.0.1:6381

swagger:
    enabled: true