spring:
    application:
        name: redis
    profiles:
        active: dev
    #session store type使用来存放session的存储方式，目前Spring boot中只支持redis方式
    #由于本应用暂无需将session放入redis的需求，故这里就可以将session store type设置为none
    session:
        store-type: none

server:
    port: 6379

logging:
    level:
        com.dzr.redis: debug
    config: classpath:logback.xml